robot_info:



- name : 'Robotis OP3'

  pybullet_joints :
    - 'l_hip_yaw'
    - 'l_hip_roll'
    - 'l_hip_pitch'
    - 'l_knee'
    - 'l_ank_pitch'
    - 'l_ank_roll'
    - 'r_hip_yaw'
    - 'r_hip_roll'
    - 'r_hip_pitch'
    - 'r_knee'
    - 'r_ank_pitch'
    - 'r_ank_roll'
    - 'l_sho_pitch'
    - 'l_sho_roll'
    - 'l_el'
    - 'r_sho_pitch'
    - 'r_sho_roll'
    - 'r_el'
    - 'head_pan'
    - 'head_tilt'

  webots_joints :
    - 'Neck'
    - 'Head'
    - 'ShoulderR'
    - 'ArmUpperR'
    - 'ArmLowerR'
    - 'ShoulderL'
    - 'ArmUpperL'
    - 'ArmLowerL'
    - 'PelvYR'
    - 'PelvR'
    - 'LegUpperR'
    - 'LegLowerR'
    - 'AnkleR'
    - 'FootR'
    - 'PelvYL'
    - 'PelvL'
    - 'LegUpperL'
    - 'LegLowerL'
    - 'AnkleL'
    - 'FootL'

  joints_enumerator :
    # pybullet
    l_hip_yaw   : 1
    l_hip_roll  : 2
    l_hip_pitch : 3
    l_knee      : 4
    l_ank_pitch : 5
    l_ank_roll  : 6
    r_hip_yaw   : 7
    r_hip_roll  : 8
    r_hip_pitch : 9
    r_knee      : 10
    r_ank_pitch : 11
    r_ank_roll  : 12
    l_sho_pitch : 13
    l_sho_roll  : 14
    l_el        : 15
    r_sho_pitch : 16
    r_sho_roll  : 17
    r_el        : 18
    head_pan    : 19
    head_tilt   : 20
    # webots
    Neck        : 19
    Head        : 20
    ShoulderR   : 16
    ArmUpperR   : 17
    ArmLowerR   : 18
    ShoulderL   : 13
    ArmUpperL   : 14
    ArmLowerL   : 15
    PelvYR      : 7
    PelvR       : 8
    LegUpperR   : 9
    LegLowerR   : 10
    AnkleR      : 11
    FootR       : 12
    PelvYL      : 1
    PelvL       : 2
    LegUpperL   : 3
    LegLowerL   : 4
    AnkleL      : 5
    FootL       : 6



- name: 'Robotis Turtlebot3'




- name: 'Boston Dynamics Spot'


